name: Github Actions 실행시켜보기

on:
  push:
    branches:
      - master

jobs:
  My-Deploy-Job:
    runs-on: ubuntu-latest

    steps:
      - name: Hello World 찍기
        run: echo "Hello World!"

      - name: 여러 명령어 문장 작성하기
        run: |
          echo "Good"
          echo "Evening"
      - name: Github 내장 변수 사용하기
        run: |
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY

      - name: 아무한테도 노출되면 안돼는 값
        run: |
          echo ${{ secrets.MY_NAME }}
          echo ${{ secrets.MY_HOBBY }}
